/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PartyMemberData
    {
        public bool valid = false;
        internal PartyMemberData()
        {
            //Made for conditional structures
        }

        internal PartyMemberData(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadInt32();
            Unk2 = reader.ReadInt32();
            Unk3 = reader.ReadByte();
            Unk4 = reader.ReadInt64();
            Unk5 = new ReadNBytesInt64(reader);
            Name = new LostArkString(reader);
            Unk7 = reader.ReadInt16();
            Unk8 = reader.ReadByte();
            Unk9 = reader.ReadByte();
            Unk10 = reader.ReadByte();
            Unk11 = reader.ReadByte();
            PartyMemberNumber = reader.ReadByte();
            Unk13 = reader.ReadInt64();
            CharacterId = reader.ReadUInt64();
            Unk15 = new ReadNBytesInt64(reader);
            Unk16 = reader.ReadByte();
            CharacterLevel = reader.ReadUInt16();
            Unk18 = reader.ReadInt32();
            Unk19 = reader.ReadInt16();
        }

        public byte Unk0 { get; }
        public int Unk1 { get; }
        public int Unk2 { get; }
        public byte Unk3 { get; }
        public long Unk4 { get; }
        public ReadNBytesInt64 Unk5 { get; } = new ReadNBytesInt64();
        public LostArkString Name { get; } = new LostArkString();
        public short Unk7 { get; }
        public byte Unk8 { get; }
        public byte Unk9 { get; }
        public byte Unk10 { get; }
        public byte Unk11 { get; }
        public byte PartyMemberNumber { get; }
        public long Unk13 { get; }
        public ulong CharacterId { get; }
        public ReadNBytesInt64 Unk15 { get; } = new ReadNBytesInt64();
        public byte Unk16 { get; }
        public ushort CharacterLevel { get; }
        public int Unk18 { get; }
        public short Unk19 { get; }
    }
}