/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PCStruct
    {
        public bool valid = false;
        internal PCStruct()
        {
            //Made for conditional structures
        }

        internal PCStruct(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadByte();
            Name = new LostArkString(reader);
            Unk2 = reader.ReadByte();
            Unk3 = reader.ReadInt16();
            Unk4 = new LostArkString(reader);
            Unk5 = reader.ReadByte();
            if(Unk5 == 1)
            {
                Unk5_0 = reader.ReadBytes(12);
            }
            Unk6 = reader.ReadInt16();
            Unk7 = reader.ReadByte();
            Unk8 = reader.ReadByte();
            Unk9 = reader.ReadInt32();
            struct_371 = new Struct_371(reader);
            Unk11 = reader.ReadInt32();
            Unk12 = reader.ReadInt32();
            struct_3 = new Struct_3(reader);
            Unk14 = reader.ReadByte();
            Unk15 = reader.ReadByte();
            Unk16 = reader.ReadInt32();
            Level = reader.ReadUInt16();
            Unk18 = reader.ReadBytes(25);
            struct_297 = new Struct_297(reader);
            PlayerId = reader.ReadUInt64();
            Unk21 = reader.ReadBytes(5);
            CharacterId = reader.ReadUInt64();
            Unk5_m = reader.ReadUInt32();
            Unk24 = reader.ReadByte();
            struct_120 = new Struct_120(reader);
            Unk26 = reader.ReadByte();
            struct_298 = new Struct_298(reader);
            Unk28 = reader.ReadByte();
            Unk29 = reader.ReadByte();
            Unk30 = reader.ReadInt32();
            Unk31 = reader.ReadByte();
            statusEffectDatas = new StatusEffectDatas(reader);
            statPair = new StatPair(reader);
            Unk34 = reader.ReadInt32();
            Unk35 = reader.ReadInt32();
            Unk36 = reader.ReadInt64();
            Unk37 = reader.ReadInt32();
            Unk38 = reader.ReadByte();
            struct_88 = new Struct_88(reader);
            Unk40 = reader.ReadInt16();
            GearLevel = reader.ReadUInt32();
            ClassId = reader.ReadUInt16();
            Heading = reader.ReadAngle();
        }

        public byte Unk0 { get; }
        public LostArkString Name { get; } = new LostArkString();
        public byte Unk2 { get; }
        public short Unk3 { get; }
        public LostArkString Unk4 { get; } = new LostArkString();
        public byte Unk5 { get; }
        public byte[] Unk5_0 { get; }
        public short Unk6 { get; }
        public byte Unk7 { get; }
        public byte Unk8 { get; }
        public int Unk9 { get; }
        public Struct_371 struct_371 { get; } = new Struct_371();
        public int Unk11 { get; }
        public int Unk12 { get; }
        public Struct_3 struct_3 { get; } = new Struct_3();
        public byte Unk14 { get; }
        public byte Unk15 { get; }
        public int Unk16 { get; }
        public ushort Level { get; }
        public byte[] Unk18 { get; }
        public Struct_297 struct_297 { get; } = new Struct_297();
        public ulong PlayerId { get; }
        public byte[] Unk21 { get; }
        public ulong CharacterId { get; }
        public uint Unk5_m { get; }
        public byte Unk24 { get; }
        public Struct_120 struct_120 { get; } = new Struct_120();
        public byte Unk26 { get; }
        public Struct_298 struct_298 { get; } = new Struct_298();
        public byte Unk28 { get; }
        public byte Unk29 { get; }
        public int Unk30 { get; }
        public byte Unk31 { get; }
        public StatusEffectDatas statusEffectDatas { get; } = new StatusEffectDatas();
        public StatPair statPair { get; } = new StatPair();
        public int Unk34 { get; }
        public int Unk35 { get; }
        public long Unk36 { get; }
        public int Unk37 { get; }
        public byte Unk38 { get; }
        public Struct_88 struct_88 { get; } = new Struct_88();
        public short Unk40 { get; }
        public uint GearLevel { get; }
        public ushort ClassId { get; }
        public Angle Heading { get; }
    }
}