/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTDeathNotify
    {
        public PKTDeathNotify(BitReader reader)
        {
            Unk0 = reader.ReadByte();
            if(Unk0 == 1)
            {
                Unk0_0 = reader.ReadByte();
            }
            TargetId = reader.ReadUInt64();
            Unk2 = reader.ReadInt64();
            Unk3 = reader.ReadByte();
            if(Unk3 == 1)
            {
                Unk3_0 = reader.ReadByte();
            }
            Unk4 = reader.ReadByte();
            Unk5 = reader.ReadInt32();
            Unk6 = reader.ReadInt16();
            SourceId = reader.ReadUInt64();
            Unk8 = reader.ReadByte();
            if(Unk8 == 1)
            {
                Unk8_0 = reader.ReadByte();
            }
        }

        public byte Unk0 { get; }
        public byte Unk0_0 { get; }
        public ulong TargetId { get; }
        public long Unk2 { get; }
        public byte Unk3 { get; }
        public byte Unk3_0 { get; }
        public byte Unk4 { get; }
        public int Unk5 { get; }
        public short Unk6 { get; }
        public ulong SourceId { get; }
        public byte Unk8 { get; }
        public byte Unk8_0 { get; }
    }
}