/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTInitEnv
    {
        public PKTInitEnv(BitReader reader)
        {
            Unk0 = reader.ReadInt32();
            Unk1 = reader.ReadInt64();
            struct_27 = new Struct_27(reader);
            struct_544 = new Struct_544(reader);
            lostArkDateTime = new LostArkDateTime(reader);
            Unk5 = reader.ReadInt32();
            Unk6 = reader.ReadByte();
            PlayerId = reader.ReadUInt64();
        }

        public int Unk0 { get; }
        public long Unk1 { get; }
        public Struct_27 struct_27 { get; } = new Struct_27();
        public Struct_544 struct_544 { get; } = new Struct_544();
        public LostArkDateTime lostArkDateTime { get; } = new LostArkDateTime();
        public int Unk5 { get; }
        public byte Unk6 { get; }
        public ulong PlayerId { get; }
    }
}