/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTPartyStatusEffectRemoveNotify
    {
        public PKTPartyStatusEffectRemoveNotify(BitReader reader)
        {
            CharacterId = reader.ReadUInt64();
            Unk1 = reader.ReadByte();
            statusEffectIds = new StatusEffectIds(reader);
            Unk3 = reader.ReadInt64();
        }

        public ulong CharacterId { get; }
        public byte Unk1 { get; }
        public StatusEffectIds statusEffectIds { get; } = new StatusEffectIds();
        public long Unk3 { get; }
    }
}