/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTRemoveObject
    {
        public PKTRemoveObject(BitReader reader)
        {
            unpublishedObjects = new UnpublishedObjects(reader);
        }

        public UnpublishedObjects unpublishedObjects { get; } = new UnpublishedObjects();
    }
}