/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTSkillStageNotify
    {
        public PKTSkillStageNotify(BitReader reader)
        {
            reader.Skip(24);
            SourceId = reader.ReadUInt64();
            reader.Skip(5);
            SkillId = reader.ReadUInt32();
            reader.Skip(11);
            Stage = reader.ReadByte();
            reader.Skip(1);
        }

        public ulong SourceId { get; }
        public uint SkillId { get; }
        public byte Stage { get; }
    }
}