/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTStatusEffectAddNotify
    {
        public PKTStatusEffectAddNotify(BitReader reader)
        {
            New = reader.ReadBool();
            Unk1 = reader.ReadInt64();
            Unk2 = reader.ReadByte();
            if(Unk2 == 1)
            {
                Unk2_0 = reader.ReadInt64();
            }
            ObjectId = reader.ReadUInt64();
            statusEffectData = new StatusEffectData(reader);
        }

        public bool New { get; }
        public long Unk1 { get; }
        public byte Unk2 { get; }
        public long Unk2_0 { get; }
        public ulong ObjectId { get; }
        public StatusEffectData statusEffectData { get; } = new StatusEffectData();
    }
}