/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class PKTStatusEffectSyncDataNotify
    {
        public PKTStatusEffectSyncDataNotify(BitReader reader)
        {
            reader.Skip(9);
            CharacterId = reader.ReadUInt64();
            reader.Skip(2);
            Value = reader.ReadUInt32();
            ObjectId = reader.ReadUInt64();
        }

        public ulong CharacterId { get; }
        public uint Value { get; }
        public ulong ObjectId { get; }
    }
}