/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_88
    {
        public bool valid = false;
        internal Struct_88()
        {
            //Made for conditional structures
        }

        internal Struct_88(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt32();
            if(Unk0 <= 512)
            {
                Unk0_0 = reader.ReadBytes(Unk0);
            }
        }

        public int Unk0 { get; }
        public byte[] Unk0_0 { get; }
    }
}