/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_677
    {
        public bool valid = false;
        internal Struct_677()
        {
            //Made for conditional structures
        }

        internal Struct_677(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadByte();
            Unk1 = new ReadNBytesInt64(reader);
            Unk2 = reader.ReadByte();
            Unk3 = reader.ReadByte();
            Unk4 = reader.ReadInt64();
            Unk5 = new ReadNBytesInt64(reader);
            Unk6 = reader.ReadInt16();
        }

        public byte Unk0 { get; }
        public ReadNBytesInt64 Unk1 { get; } = new ReadNBytesInt64();
        public byte Unk2 { get; }
        public byte Unk3 { get; }
        public long Unk4 { get; }
        public ReadNBytesInt64 Unk5 { get; } = new ReadNBytesInt64();
        public short Unk6 { get; }
    }
}