/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_674
    {
        public bool valid = false;
        internal Struct_674()
        {
            //Made for conditional structures
        }

        internal Struct_674(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadByte();
            lostArkString = new LostArkString(reader);
            Unk3 = reader.ReadByte();
            struct_88 = new Struct_88(reader);
            struct_298 = new Struct_298(reader);
            Unk6 = reader.ReadInt64();
            Unk7 = reader.ReadInt16();
        }

        public byte Unk0 { get; }
        public byte Unk1 { get; }
        public LostArkString lostArkString { get; } = new LostArkString();
        public byte Unk3 { get; }
        public Struct_88 struct_88 { get; } = new Struct_88();
        public Struct_298 struct_298 { get; } = new Struct_298();
        public long Unk6 { get; }
        public short Unk7 { get; }
    }
}