/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArkLogger.Types;

namespace LostArkLogger
{
    public class Struct_371
    {
        public bool valid = false;
        internal Struct_371()
        {
            //Made for conditional structures
        }

        internal Struct_371(BitReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            if(Unk0 <= 5)
            {
                for(var i = 0; i < Unk0; i++)
                {
                    struct_677.Add(new Struct_677(reader));
                }
            }
        }

        public short Unk0 { get; }
        public List<Struct_677> struct_677 { get; } = new List<Struct_677>();
    }
}